align-spectra:
  SNR: 2
  half-window-size: 20
  noise-method: MAD
  tolerance: 0.002
  warping-method: lowess
database:
  local-enabled: true
  local-file-name: pathogens.db
  remote-database: pathogensdb
  remote-host: 127.0.0.1
  remote-password: password
  remote-port: 3306
  remote-username: admin
options:
  cancel-if-null-valued-spectra: false
  export-feature-matrix-CSV-file: false
  num-components: 10
  plot-PCA: false
  plot-baseline: false
  plot-dendrogram: false
  plot-noise: false
  scaling-factor: TIC
  similarity-threshold: 0.95
  trim-lower-bounds: 200
  trim-upper-bounds: 1995
